### PR TITLE
Update sounds

### PR DESCRIPTION
**Pull request by joshwalawender**
Sounds for macOS.  Also I changed the default config file (`keck_vnc_config.yaml`) to point to the soft link for linux and to have commented out lines for macOS.

### CODE REVIEW

**Review by joshjriley — APPROVED** [review]
An idea: if 'soundplayer'  is not set in config, we could perhaps detect OS and choose the appropriate soundplay executable.

**Review by joshjriley — APPROVED** [review]
Good catch on the commas in the README.  Sorry i forget to update that.

I think the setup is getting to be a bit of a long read.  Might be worth going thru it again to make it all more concise if possible.

**Comment by joshwalawender** [comment]
Good idea about checking the OS.  I'll play with that and maybe add it in.

I've just added a command to test sound.  I can only test that the code works on macOS, so if someone can test linux (@klanclos ?), that would be great.

**Comment by joshwalawender** [comment]
Can anyone confirm that this branch works with sound on linux?  Also need to confirm that my `p` command to play a test sound works on linux as well.  If they work, I can merge this in to dev.

**Pull request merged**
