### PR TITLE
Soundplay renaming

### PR DESCRIPTION
**Pull request by klanclos**
Move the soundplay binaries to names specific to an operating system + architecture combination. Auto-detect the correct soundplay binary if one is not set; this eliminates the need for the symlink to be managed by users. Will fall back on using the symlink the arch-specific binary is not found.

Use soundplay to play test sounds instead of aplay.

### CODE REVIEW

**Comment by joshwalawender** [comment]
Failing on my macOS install.  My config file sound section:
```
soundplayer: 'soundplay.darwin.x86_64'
aplay: '/usr/bin/afplay -v %v %s'
```

No obvious problems in the log, but I get no instrument sounds.  I tried the `p` command and got:

```
> p
     INFO: Recieved command "p"
     INFO: Recieved command "p"
     INFO: Calling: /Users/joshw/git/RemoteObserving/soundplayer/soundplay.darwin.x86_64 -l /usr/bin/afplay -v %v %s
Note: using starkit mode "starpack" -- therefore, we
      do not try to load soundboard values from services file.
Using: afplay -v %v %s
Use:
    main.tcl [-h] [-l] [-x] [-t] [-s host[:port]] [-d workdir] [-pi | -px [playcommand]] [-T tag,...]...
Options
  -h        	Print this help info, then exit.

  -t        	If there is another soundplay'er connected from this host to
		the soundboard, take the connection (force the other to close).

  -l        	Instead of connecting to the soundboard, verify local-side
		functionality by playing a test sound, then exiting.

  -s host[:port]	Connect to this host:port.
		When not running under a starkit, defaults are:
		o  host from readremote lookup of key "soundboard_host";
		    if not defined, use "localhost".
		o  port from readremote lookup of key "soundboard_player_port";
		    if not defined, use 9798.
		When running under a starkit:
		o  The default host:port = "localhost:9798"
```
etc.

**Comment by klanclos** [comment]
The play_test_sound() method was missing the -px argument when appending aplay options. I pushed a change putting that back in; try again? If it still doesn't work you might want to play around with invoking soundplay directly to see which combination of command line arguments are required.

**Comment by joshwalawender** [comment]
The `p` command now works if my local config contains: `aplay: '/usr/bin/afplay -v %v %s'`.  Does soundplay carry that argument through?  It doesn't look like it from the logs:

```
2020-03-24 22:35:27,471 UT - DEBUG: Soundplay cmd: ['/Users/joshw/git/RemoteObserving/soundplayer/soundplay.darwin.x86_64', '-s', 'localhost:50002', '-T', 'mosfire', '-px', 'aplay']
```

Instrument sounds do not work.

**Comment by joshwalawender** [comment]
see #42 for fix

**Comment by joshwalawender** [comment]
Running the `p` command spits some STDOUT to the terminal where the app is running.  Can we capture and log instead?

```
Note: using starkit mode "starpack" -- therefore, we
      do not try to load soundboard values from services file.
Using: afplay -v %v %s
Using soundboard host: localhost
Using soundboard port: 9798
Sound file "testsound.au" saved to /Users/joshw/.soundboard

PLAYRESPONSE 0 Command template=/usr/bin/afplay -v 1 %s
Command=/usr/bin/afplay -v 1 /Users/joshw/.soundboard/testsound.au
```

Otherwise looks pretty good.

**Comment by joshwalawender** [comment]
@klanclos Check PR #43 for a fix to my above request.  If it looks good to you will merge here, then merge to dev.

**Pull request merged**
