### PR TITLE
Add command to upload log file to keck

### PR DESCRIPTION
**Pull request by joshwalawender**
Added the `u` command to upload the log file for that session.  This provides an easy troubleshooting tool (assuming of course that the first few steps of firewall authentication and SSH connections have succeeded).

This uploads the log file to the home directory of the numbered account for the VNC sessions on the VNC server.

### CODE REVIEW

**Comment by joshjriley** [comment]
Great idea.  I'll try this out soon.  My first thoughts are:
- Append some identifier to filename based on client system info/ip?
- Upload these all to the 'kvnc' account instead?
- Put these in a common folder instead of into the root of the home folder.
- Automate this on crashes/errors.
- Also notify remote observing via email command sent from keck server using ssh command.
- Expand on this idea and send usage data to another folder and/or append to one usage log file.

**Comment by joshwalawender** [comment]
All good suggestions.  I was thinking about the first point (system IDs) last night and while it would be nice, it is probably not critical since the date and instrument account really narrows down who was connecting and the logs contain the system hostname.  I also wasn't sure how else to tag each system with an ID without adding complication.

I'm a bit torn on where they should go.  Part of me says it makes sense for them to go to some central location, but the advantage of the home directory of the account in use for the night is that the SA or SWOC trying to troubleshoot doesn't have to remember a special location for the logs and can find them easily.  Also, there's no risk of the destination folder disappearing at some future point during a system change or upgrade.  The files would also get cleared out by the conk process periodically, so they would not build up (I didn't intend Keck to become a repository for the log files).

**Comment by joshjriley** [comment]
Tried it with ssh key configured (nominal use) and upload_log doesn't work b/c user never entered self.vnc_password.  So, actually, it might not work after all to upload to instr account home directories.  If you can't get it to work, you can change it to used the self.SSH_KEY_ACCOUNT 'kvnc' user and upload all files to that home dir.  I did a test of that and created a ~/remote-logs/ dir for kvnc if you want to go that route.  If we want to get fancy, we could have upload_log also execute a simple mailx command to mainland_admin after the file is ftp'd reminding them where the log file is.

**Comment by joshjriley** [comment]
Here is my test with 'kvnc' plus an automated email with log file attached:   
`    def upload_log(self):
        ok = False
        try:
            user = self.SSH_KEY_ACCOUNT if self.is_ssh_key_valid else self.args.account
            pw   = None                 if self.is_ssh_key_valid else self.vnc_password

            client = paramiko.SSHClient()
            client.load_system_host_keys()
            client.set_missing_host_key_policy(paramiko.WarningPolicy())
            client.set_missing_host_key_policy(paramiko.AutoAddPolicy())
            client.connect(
                self.vncserver,
                port = 22, 
                timeout = 6, 
                key_filename=self.ssh_pkey,
                username = user, 
                password = pw)
            sftp = client.open_sftp()
            log.info('  Connected SFTP')

            logfile_handlers = [lh for lh in log.handlers if 
                                isinstance(lh, logging.FileHandler)]
            logfile = Path(logfile_handlers.pop(0).baseFilename)
            destination = f'remote-logs/{logfile.name}'
            sftp.put(logfile, destination)
            log.info(f'  Uploaded {logfile.name}')
            log.info(f'  to {user}@{self.vncserver}:~/{destination}')            
            ok = True
        except TimeoutError:
            log.error('  Timed out trying to upload log file')
        except Exception as e:
            log.error('  Unable to upload logfile: ' + str(e))

        if not ok: return

        try: 
            subject = f"KRO log uploaded to {user}@{self.vncserver}:~/{destination}"
            cmd = f'mailx -s "{subject}" jriley@keck.hawaii.edu < {destination}'
            data = self.do_ssh_cmd(cmd, self.SSH_KEY_SERVER, self.SSH_KEY_ACCOUNT, None)
        except Exception as e:
            log.debug('  Unable to email logfile: ' + str(e))
`

**Comment by joshwalawender** [comment]
I've added the code to handle ssh key properly, but I did not include the email code since I don't want to worry about whether there is email set up.

**Comment by joshjriley** [comment]
Tried it out again.  Looks good to me.  I put an AAREADME in destination folder saying not to delete the folder.

**Review by joshjriley — APPROVED** [review]

**Comment by joshwalawender** [comment]
Merged manually to handle conflicts.

**Pull request closed without merging**
